auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('Create_listing', views.Create_listing, name='Create_listing'),
    path('Category_view', views.Category_view, name='Category_view'),
   path("<str:category_id>", views.Category_list, name='Category_list'),
   path("Bid", views.Place_bid, name="Bid"),
   path("Comment", views.User_comment, name="User_comment"),
   path("Watchlist", views.User_watchlist, name="User_watchlist"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from PIL import Image
from PIL.Image import core as _imaging
from django.conf import settings
from django.conf.urls.static import static


class User(AbstractUser):
    pass

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=25)


    def __str__(self):
        return f"{self.category}"

class Auction(models.Model):
    id = models.AutoField(primary_key=True)

    STATUS = (
        ('Active', 'Active'),
        ('Closed', 'Closed'),
        ('Sold', 'Sold'),
    )
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()
    active = models.CharField(max_length=25, choices=STATUS)
    selectcategory = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media", blank=True)
    date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f"{self.seller}, {self.title}, {self.description}, {self.active}, {self.price}, {self.date},{self.active}, {self.image}"

class Bid(models.Model):
    
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_name")
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_bids")
    product_price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.buyer}, {self.product_price}, {self.date}"

class Comment(models.Model):
    
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

    def __str__(self):
        return f"{self.user},  {self.comment}, {self.product_id}"

class Watchlist(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_watchlist")
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_watchlist")

    def __str__(self):
        return f"{self.user}, {self.product_id}, {self.id}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import User,Auction,Category,Bid
from django.core.files.storage import FileSystemStorage
import os, os.path
from .models import User


def index(request):
    return render(request, "auctions/index.html",{
        "auctions":Auction.objects.all(),
    })



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def Create_listing(request):
    if request.method == "POST":
        product = Auction()
        category = Category.objects.get(id=int(request.POST["category"]))

        product.title = request.POST["title"]
        product.seller = request.user
        product.description= request.POST["description"]
        product.active = request.POST["active"]
        product.price = request.POST["price"]
        product.image = request.FILES['image']
        product.selectcategory = category
        product.save()

        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/create.html",{
            "categories": Category.objects.all()
        })
def Category_view(request):
    return render(request,"auctions/category.html",{
        "category": Category.objects.all()
    })

def Category_list(request,category_id):
    products = Auction.objects.filter(selectcategory=category_id)
    if len(products) >= 1:
        return render(request, "auctions/category_list.html",{
        "products": products,
    })

    else:
        return render(request, "auctions/category_list.html",{
        "message": "No listings found!"
    })

def Place_bid(request):
    pass

def User_comment(request):
    pass

def User_watchlist(request):
    show_products = Watchlist.objects.filter(user = request.user)
    if show_products:
        return render(request, "auctions/watchlist.html", {
            'liked_products': show_products
        })
    else:
        return render(request, "auctions/watchlist.html", {
            'message': 'Empty'
        })


def addWatchlist(request, id):
    q = Auction.objects.get(id = id)
    Watchlist.objects.create(user = request.user, product_id = q)
    return HttpResponseRedirect(reverse("index"))



          


        

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{%block body%}
<ul >
    {% for cat in category%}
     <li value="{{cat.id}}">
         <a href="{% url 'Category_list' category_id=cat.id %}">{{cat}}</a>
        </li>
    {%endfor%}
</ul>

{%endblock%}

auctions/templates/auctions/category_list.html
{% extends "auctions/layout.html" %}

{%block body%}

<br>

{% if message  %}

<div class="alert alert-danger">

    {{message}}

</div>

{%endif%}

{% for product in products%}

<div>       
    <h3> {{product.title}} </h3><br>
    <img src="{{product.image.url}}" alt="" width="300"> 
</div>
<div>
    <li>{{product.date}}</li>
</div>
<div>
    Description
   <li>{{product.description}}</li> 
</div>
<div>Seller
    <li>{{product.seller}}</li>
</div>

<div>Category
    <li>{{product.selectcategory}}</li>
</div>
<div>Status
    <li>{{product.active}}</li>
</div>
{%endfor%}
{%endblock%}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}

{% if message %}
<div>{{ message }}</div>
{% endif %}
    <div class="text-left">

        <form action="{% url 'Create_listing' %}" method="POST" enctype=multipart/form-data>
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="title" placeholder="Title">
            </div>
            <div class="form-group">
                <label class="required">Description:</label>
                <textarea class="form-control" name="description" rows="4" placeholder="Description"></textarea>
            </div>
            <div class="form-group">
                <label class="required">Category:</label>
                <select class="form-control" name="category">
                    {% for category in categories %}
                      <option value="{{category.id}}">{{category.category}}</option>
                    {% endfor %}
                  </select>
            </div>
            <div class="form-group">
                <label class="required">Price:</label>
                <input class="form-control" type="text" name="price" placeholder="price">
            </div>
            <div class="form-group">
                <label class="required" for="id_active">Active:</label>
                <select name="active" required="" id="id_active">
                    <option value="" selected="">---------</option>
                  
                    <option value="Active">Active</option>
                  
                    <option value="Closed">Closed</option>
                  
                    <option value="Sold">Sold</option>
                  
                  </select>
            </div>
            <div class="form-group">
                <label class="required">Image:</label>
                <input class="form-control" type="file" name="image" placeholder="Image">
            </div>
            <input class="btn btn-primary" type="submit" value="Create">
        </form>
    </div>
</div>
<!-- End Jumbotron -->

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <div>
            {% for auction in auctions %}
            {%if auction.active == "Active" %}
            <div class="card-deck">
                <div class="card" style="width: 18rem;">
                    <div>
                        <button class="watchlist">Add to Watchlist</button>
                        <h3 class="item_title"> {{auction.title}} </h3><br>
                        <img class="card-img-top" src="{{auction.image.url}}" alt="" width="300"> 
                    </div>
                    <br>
                    <div class="card-body">
                        <strong>Description</strong>
                       <div>{{auction.description}}</div> 
                       <br>
                       <strong>Price</strong>
                       <div>{{auction.price}}</div>
                       
                    </div>
                </div>
            </div>
           
            <br>
            {%endif%}
            {%endfor%}
    </div>
    
 
    
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>

    <body class="container">

        <h1 class="headingCenter">Welcome to W-bay Auctions.</h1>

        <div style="text-align: right;">
            {% if user.is_authenticated %}
                Signed in as <br><strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>

        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Create_listing' %}">Create-Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Category_view' %}">Categories</a>
                    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'User_watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}

        </ul>

        <hr>

        {% block body %}
        {% endblock %}

    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}